In [1]:
import pandas as pd
print(pd.__version__)

3.0.3

In [ ]:
s=pd.Series(
    [120, 85, 200, 45],
    index=["ene", "feb", "mar", "abr"],
    name="ventas"
)
print(s["mar"]) # acceso por etiqueta

200
ene    145.20
feb    102.85
mar    242.00
abr     54.45
Name: ventas, dtype: float64
112.5 200

In [5]:
print(s[2:])

mar    200
abr     45
Name: ventas, dtype: int64

In [6]:
print(s * 1.21) # vectorizado: IVA

ene    145.20
feb    102.85
mar    242.00
abr     54.45
Name: ventas, dtype: float64

In [9]:
s.mean()

np.float64(112.5)

In [10]:
s.max()

np.int64(200)

## DATA FRAME

In [2]:
import numpy as np

In [13]:
# a) Desde un diccionario de listas (la más habitual)
df = pd.DataFrame(
    {
        "producto": ["Laptop", "Monitor", "Teclado"],
        "unidades": [3, 7, 12],
        "precio": [1200.0, 320.0, 95.0],
    }
)
print(df)

  producto  unidades  precio
0   Laptop         3  1200.0
1  Monitor         7   320.0
2  Teclado        12    95.0

In [14]:
df.head()

  producto  unidades  precio
0   Laptop         3  1200.0
1  Monitor         7   320.0
2  Teclado        12    95.0

In [15]:
# b) Desde una lista de diccionarios (típico de una API JSON)
df2 = pd.DataFrame(
    [
        {"producto": "Laptop", "unidades": 3},
        {"producto": "Monitor", "unidades": 7}
    ]
)
df2.head()

  producto  unidades
0   Laptop         3
1  Monitor         7

In [16]:
# c) Desde una lista de listas, indicando las columnas
df3 = pd.DataFrame(
    [
        ["Laptop", 3], 
        ["Monitor", 7]
    ],
 columns=["producto", "unidades"]
)
df3.head()

  producto  unidades
0   Laptop         3
1  Monitor         7

In [17]:
# d) Desde un array de NumPy
df4 = pd.DataFrame(np.random.rand(3, 2), columns=["x", "y"])
df4.head()

          x         y
0  0.051384  0.994875
1  0.722266  0.873875
2  0.629028  0.150016

## CREACION DE COLUMNAS

In [18]:
df["importe"]=df["unidades"]*df["precio"]
df.head()

  producto  unidades  precio  importe
0   Laptop         3  1200.0   3600.0
1  Monitor         7   320.0   2240.0
2  Teclado        12    95.0   1140.0

In [21]:
df.shape

(3, 4)

In [22]:
df["dummy"]=6
df.head()

  producto  unidades  precio  importe  dummy
0   Laptop         3  1200.0   3600.0      6
1  Monitor         7   320.0   2240.0      6
2  Teclado        12    95.0   1140.0      6

In [24]:
df["dummy2"]=[5,4,6]
df.head()

  producto  unidades  precio  importe  dummy  dummy2
0   Laptop         3  1200.0   3600.0      6       5
1  Monitor         7   320.0   2240.0      6       4
2  Teclado        12    95.0   1140.0      6       6

In [35]:
# 1. Crea una Series con las temperaturas [21, 24, 19, 27, 30] e índice de lunes a viernes.
temperaturas= pd.Series(
    [21,24,19,27,30],
    index=["Lunes","Martes","Miercoles","Jueves","Viernes"]
)
print(temperaturas)
# 2. Muestra la media, el máximo y el día que corresponde al máximo (usa .idxmax()).
print("Media:",temperaturas.mean())
print("Maximo:",temperaturas.max())
print("Dia maximo:",temperaturas.idxmax())
# 3. Crea un DataFrame con 5 productos: nombre, categoría, stock y precio(inventados).
df = pd.DataFrame(
    {
        "nombre": ["Laptop", "Monitor", "Teclado","Mouse","Fuente de poder"],
        "categoria": ["Tegnologia", "Tegnologia", "Tegnologia","Tegnologia","Tegnologia"],
        "stock": [3, 7, 12,1,0],
        "precio": [1200.0, 320.0, 95.0,12,15]
    }
)
df.head()
# 4. Añade una columna valor_stock = stock × precio.
df["valor_stock"]=df["stock"]*df["precio"]
print(df.head())
# 5. Imprime la forma del DataFrame y la lista de nombres de columna.
print(df.shape)
print(df.columns)
print(df.columns.to_list())

Lunes        21
Martes       24
Miercoles    19
Jueves       27
Viernes      30
dtype: int64
Media: 24.2
Maximo: 30
Dia maximo: Viernes
            nombre   categoria  stock  precio  valor_stock
0           Laptop  Tegnologia      3  1200.0       3600.0
1          Monitor  Tegnologia      7   320.0       2240.0
2          Teclado  Tegnologia     12    95.0       1140.0
3            Mouse  Tegnologia      1    12.0         12.0
4  Fuente de poder  Tegnologia      0    15.0          0.0
(5, 5)
Index(['nombre', 'categoria', 'stock', 'precio', 'valor_stock'], dtype='str')
['nombre', 'categoria', 'stock', 'precio', 'valor_stock']

## LECTURA DE CSV

In [15]:
df = pd.read_csv(
    r"C:\Users\SAHUA\Documents\datascience-g8\01-python-intro\data\ventas.csv",
    dtype={"precio_unitario":"float64"}
    )
df.head()

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130.0,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320.0,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280.0,0.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200.0,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130.0,0.1

In [5]:
df.tail(5)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45,0.00
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200,0.05
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320,0.05
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320,0.00
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45,0.00

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   fecha            1200 non-null   str
 1   region           1200 non-null   str
 2   vendedor         1182 non-null   str
 3   producto         1200 non-null   str
 4   categoria        1200 non-null   str
 5   unidades         1200 non-null   int64
 6   precio_unitario  1200 non-null   float64
 7   descuento        1165 non-null   float64
dtypes: float64(2), int64(1), str(5)
memory usage: 75.1 KB

In [7]:
df.describe()

          unidades  precio_unitario    descuento
count  1200.000000      1200.000000  1165.000000
mean      7.275833       387.412500     0.047639
std       4.054024       346.020316     0.056273
min       1.000000        45.000000     0.000000
25%       4.000000       130.000000     0.000000
50%       7.000000       280.000000     0.000000
75%      11.000000       450.000000     0.100000
max      14.000000      1200.000000     0.150000

In [ ]:
df.sample(10)###da una muestra aleatoria de toda la base de  datos

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
654,2024-07-19,Sur,Luis Gomez,Tablet Air,Tecnologia,14,640,0.10
425,2024-05-15,Sur,Ana Torres,Raton Ergo,Accesorios,10,45,0.10
33,2024-01-11,Sur,Javier Sanz,Laptop Pro,Tecnologia,5,1200,NaN
266,2024-03-24,Este,Sofia Leon,Laptop Pro,Tecnologia,10,1200,0.10
138,2024-02-13,Norte,Ana Torres,Auriculares,Accesorios,4,130,0.00
183,2024-02-23,Este,Javier Sanz,Silla Ergo,Mobiliario,12,280,0.10
844,2024-09-17,Este,Sofia Leon,Tablet Air,Tecnologia,12,640,0.10
428,2024-05-15,Centro,Ana Torres,Raton Ergo,Accesorios,9,45,0.00
41,2024-01-14,Norte,Pedro Diaz,Escritorio,Mobiliario,5,450,0.00
847,2024-09-19,Centro,Sofia Leon,Silla Ergo,Mobiliario,11,280,0.05

In [ ]:
df.describe(include='object')###incluye str , estadisticas no numericas

C:\Users\SAHUA\AppData\Local\Temp\ipykernel_35852\545597387.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')###incluye str

             fecha region    vendedor    producto   categoria
count         1200   1200        1182        1200        1200
unique         349      5           8           8           3
top     2024-02-21  Norte  Marta Ruiz  Silla Ergo  Tecnologia
freq             9    305         170         177         447

In [10]:
df["region"].unique()

<StringArray>
['Oeste', 'Sur', 'Centro', 'Norte', 'Este']
Length: 5, dtype: str

In [ ]:
df["region"].nunique()## cuantos elementos hay en ese

5

In [12]:
df["region"].value_counts()

region
Norte     305
Centro    272
Sur       240
Oeste     203
Este      180
Name: count, dtype: int64

In [13]:
df["producto"].value_counts()

producto
Silla Ergo     177
Monitor 27     159
Auriculares    158
Tablet Air     149
Raton Ergo     146
Laptop Pro     139
Escritorio     139
Teclado Mec    133
Name: count, dtype: int64

In [14]:
df["producto"].mode()

0    Silla Ergo
Name: producto, dtype: str

## Seleccionar columnas

In [17]:
df["producto"]

0       Auriculares
1        Monitor 27
2        Silla Ergo
3        Laptop Pro
4       Auriculares
           ...
1195     Raton Ergo
1196     Laptop Pro
1197     Monitor 27
1198     Monitor 27
1199     Raton Ergo
Name: producto, Length: 1200, dtype: str

In [19]:
df[["fecha","region","unidades"]]

           fecha  region  unidades
0     2024-01-02   Oeste         5
1     2024-01-02     Sur        14
2     2024-01-02  Centro         1
3     2024-01-02  Centro        10
4     2024-01-03     Sur         2
...          ...     ...       ...
1195  2024-12-30    Este         4
1196  2024-12-30    Este        13
1197  2024-12-31   Oeste         2
1198  2024-12-31   Norte         6
1199  2024-12-31   Norte         8

[1200 rows x 3 columns]

In [21]:
df.head(2)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130.0,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320.0,0.0

In [ ]:
df.loc[0]## devulve la primera fila

fecha               2024-01-02
region                   Oeste
vendedor            Pedro Diaz
producto           Auriculares
categoria           Accesorios
unidades                     5
precio_unitario          130.0
descuento                  0.0
Name: 0, dtype: object

In [22]:
df.loc[0:4]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130.0,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320.0,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280.0,0.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200.0,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130.0,0.1

In [26]:
df.loc[0: 2,["producto","unidades"]]

      producto  unidades
0  Auriculares         5
1   Monitor 27        14
2   Silla Ergo         1

In [27]:
df.loc[:,["producto","unidades"]]

         producto  unidades
0     Auriculares         5
1      Monitor 27        14
2      Silla Ergo         1
3      Laptop Pro        10
4     Auriculares         2
...           ...       ...
1195   Raton Ergo         4
1196   Laptop Pro        13
1197   Monitor 27         2
1198   Monitor 27         6
1199   Raton Ergo         8

[1200 rows x 2 columns]

In [28]:
df.tail()

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45.0,0.00
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200.0,0.05
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320.0,0.05
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320.0,0.00
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45.0,0.00

In [31]:
df.iloc[-5:,3:6]### iloc si usa la posicion y no por etiqueta  df.iloc[-1,["region"]]<- esto no

        producto   categoria  unidades
1195  Raton Ergo  Accesorios         4
1196  Laptop Pro  Tecnologia        13
1197  Monitor 27  Tecnologia         2
1198  Monitor 27  Tecnologia         6
1199  Raton Ergo  Accesorios         8

## Ordenar dataframe

In [32]:
df.sort_values("unidades", ascending=False)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
420,2024-05-14,Este,Javier Sanz,Monitor 27,Tecnologia,14,320.0,0.10
309,2024-04-07,Norte,Elena Mora,Tablet Air,Tecnologia,14,640.0,0.05
607,2024-07-07,Centro,Javier Sanz,Auriculares,Accesorios,14,130.0,0.05
604,2024-07-05,Sur,Elena Mora,Laptop Pro,Tecnologia,14,1200.0,0.00
601,2024-07-05,Sur,Pedro Diaz,Monitor 27,Tecnologia,14,320.0,0.05
...,...,...,...,...,...,...,...,...
447,2024-05-23,Oeste,Marta Ruiz,Silla Ergo,Mobiliario,1,280.0,0.00
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280.0,0.00
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200.0,0.10
407,2024-05-06,Este,Elena Mora,Laptop Pro,Tecnologia,1,1200.0,0.05
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280.0,0.00

In [33]:
df.sort_values(["region","unidades"], ascending=[True,False])

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
76,2024-01-27,Centro,Javier Sanz,Escritorio,Mobiliario,14,450.0,0.00
83,2024-01-30,Centro,Elena Mora,Auriculares,Accesorios,14,130.0,0.10
162,2024-02-19,Centro,Elena Mora,Monitor 27,Tecnologia,14,320.0,0.15
391,2024-04-30,Centro,Carlos Vega,Silla Ergo,Mobiliario,14,280.0,0.00
446,2024-05-23,Centro,Luis Gomez,Raton Ergo,Accesorios,14,45.0,0.05
...,...,...,...,...,...,...,...,...
1044,2024-11-09,Sur,Sofia Leon,Teclado Mec,Accesorios,1,95.0,0.10
1079,2024-11-26,Sur,Elena Mora,Tablet Air,Tecnologia,1,640.0,0.15
1094,2024-12-01,Sur,Marta Ruiz,Silla Ergo,Mobiliario,1,280.0,0.00
1104,2024-12-03,Sur,Pedro Diaz,Monitor 27,Tecnologia,1,320.0,0.05
1126,2024-12-08,Sur,Pedro Diaz,Escritorio,Mobiliario,1,450.0,0.00

In [39]:
df.sort_values("unidades", ascending=False).iloc[:5,:]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
420,2024-05-14,Este,Javier Sanz,Monitor 27,Tecnologia,14,320.0,0.10
309,2024-04-07,Norte,Elena Mora,Tablet Air,Tecnologia,14,640.0,0.05
607,2024-07-07,Centro,Javier Sanz,Auriculares,Accesorios,14,130.0,0.05
604,2024-07-05,Sur,Elena Mora,Laptop Pro,Tecnologia,14,1200.0,0.00
601,2024-07-05,Sur,Pedro Diaz,Monitor 27,Tecnologia,14,320.0,0.05

In [ ]:
df.nlargest(5,"unidades")# en este te ordena por unidaes y tambien por el indice no como sorted, pero es para numericos

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320.0,0.0
62,2024-01-21,Este,Elena Mora,Silla Ergo,Mobiliario,14,280.0,0.0
63,2024-01-21,Este,Pedro Diaz,Silla Ergo,Mobiliario,14,280.0,0.1
75,2024-01-26,Sur,Luis Gomez,Escritorio,Mobiliario,14,450.0,0.0
76,2024-01-27,Centro,Javier Sanz,Escritorio,Mobiliario,14,450.0,0.0

In [ ]:
df.nsmallest(5,"unidades")## este muestra desde las ultimas y nlargest las mayores no se coloca ascending=False

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280.0,0.0
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280.0,0.0
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200.0,0.1
17,2024-01-06,Oeste,Marta Ruiz,Laptop Pro,Tecnologia,1,1200.0,0.0
26,2024-01-09,Centro,Sofia Leon,Teclado Mec,Accesorios,1,95.0,0.0