In [1]:
import pandas as pd

In [2]:
ventas = pd.read_csv(r"C:\Users\SAHUA\Documents\datascience-g8\01-python-intro\data\ventas.csv",
    dtype={"precio_unitario":"float64"})

In [3]:
ventas.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   fecha            1200 non-null   str
 1   region           1200 non-null   str
 2   vendedor         1182 non-null   str
 3   producto         1200 non-null   str
 4   categoria        1200 non-null   str
 5   unidades         1200 non-null   int64
 6   precio_unitario  1200 non-null   float64
 7   descuento        1165 non-null   float64
dtypes: float64(2), int64(1), str(5)
memory usage: 75.1 KB

In [10]:
ventas[ventas["vendedor"].isna()|ventas["descuento"].isna()]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
33,2024-01-11,Sur,Javier Sanz,Laptop Pro,Tecnologia,5,1200.0,NaN
72,2024-01-25,Oeste,Ana Torres,Teclado Mec,Accesorios,12,95.0,NaN
78,2024-01-28,Sur,Pedro Diaz,Tablet Air,Tecnologia,3,640.0,NaN
79,2024-01-29,Oeste,NaN,Raton Ergo,Accesorios,14,45.0,0.10
82,2024-01-30,Oeste,Pedro Diaz,Laptop Pro,Tecnologia,7,1200.0,NaN
98,2024-02-03,Centro,Ana Torres,Monitor 27,Tecnologia,1,320.0,NaN
102,2024-02-03,Norte,Ana Torres,Raton Ergo,Accesorios,11,45.0,NaN
109,2024-02-04,Este,Ana Torres,Raton Ergo,Accesorios,12,45.0,NaN
123,2024-02-09,Este,Sofia Leon,Silla Ergo,Mobiliario,14,280.0,NaN
135,2024-02-13,Este,Marta Ruiz,Laptop Pro,Tecnologia,8,1200.0,NaN
161,2024-02-18,Oeste,NaN,Silla Ergo,Mobiliario,1,280.0,0.05
203,2024-02-28,Norte,NaN,Raton Ergo,Accesorios,4,45.0,0.10
222,2024-03-04,Centro,Marta Ruiz,Laptop Pro,Tecnologia,12,1200.0,NaN
224,2024-03-05,Centro,Ana Torres,Raton Ergo,Accesorios,1,45.0,NaN
239,2024-03-11,Este,Javier Sanz,Escritorio,Mobiliario,3,450.0,NaN
271,2024-03-26,Sur,Javier Sanz,Silla Ergo,Mobiliario,11,280.0,NaN
283,2024-03-28,Este,Javier Sanz,Tablet Air,Tecnologia,2,640.0,NaN
310,2024-04-08,Oeste,Sofia Leon,Laptop Pro,Tecnologia,10,1200.0,NaN
405,2024-05-05,Norte,Carlos Vega,Escritorio,Mobiliario,9,450.0,NaN
424,2024-05-14,Centro,Sofia Leon,Monitor 27,Tecnologia,9,320.0,NaN
456,2024-05-28,Oeste,NaN,Tablet Air,Tecnologia,5,640.0,0.00
530,2024-06-16,Este,Ana Torres,Teclado Mec,Accesorios,9,95.0,NaN
535,2024-06-17,Este,Luis Gomez,Escritorio,Mobiliario,1,450.0,NaN
549,2024-06-20,Oeste,NaN,Raton Ergo,Accesorios,14,45.0,0.10
553,2024-06-22,Norte,NaN,Raton Ergo,Accesorios,7,45.0,0.05
571,2024-06-28,Este,NaN,Laptop Pro,Tecnologia,13,1200.0,0.00
577,2024-06-29,Este,NaN,Tablet Air,Tecnologia,8,640.0,0.00
635,2024-07-14,Centro,Pedro Diaz,Monitor 27,Tecnologia,5,320.0,NaN
639,2024-07-16,Norte,NaN,Raton Ergo,Accesorios,5,45.0,0.10
660,2024-07-21,Sur,NaN,Monitor 27,Tecnologia,14,320.0,0.00
668,2024-07-23,Sur,Javier Sanz,Auriculares,Accesorios,6,130.0,NaN
678,2024-07-27,Norte,Marta Ruiz,Laptop Pro,Tecnologia,3,1200.0,NaN
720,2024-08-09,Norte,Elena Mora,Teclado Mec,Accesorios,8,95.0,NaN
746,2024-08-18,Centro,NaN,Escritorio,Mobiliario,13,450.0,0.15
758,2024-08-20,Centro,NaN,Silla Ergo,Mobiliario,14,280.0,0.00
781,2024-08-28,Norte,NaN,Laptop Pro,Tecnologia,5,1200.0,0.00
795,2024-09-01,Oeste,Ana Torres,Silla Ergo,Mobiliario,6,280.0,NaN
803,2024-09-04,Sur,Ana Torres,Auriculares,Accesorios,5,130.0,NaN
814,2024-09-07,Este,Marta Ruiz,Escritorio,Mobiliario,6,450.0,NaN
830,2024-09-13,Sur,Javier Sanz,Monitor 27,Tecnologia,9,320.0,NaN
876,2024-09-26,Norte,Carlos Vega,Escritorio,Mobiliario,2,450.0,NaN
881,2024-09-27,Norte,Marta Ruiz,Silla Ergo,Mobiliario,7,280.0,NaN
884,2024-09-27,Este,Marta Ruiz,Escritorio,Mobiliario,7,450.0,NaN
904,2024-10-05,Sur,Ana Torres,Tablet Air,Tecnologia,6,640.0,NaN
935,2024-10-12,Sur,NaN,Laptop Pro,Tecnologia,8,1200.0,0.15
942,2024-10-14,Este,Pedro Diaz,Teclado Mec,Accesorios,2,95.0,NaN
958,2024-10-18,Oeste,NaN,Monitor 27,Tecnologia,13,320.0,0.15
991,2024-10-29,Sur,NaN,Silla Ergo,Mobiliario,1,280.0,NaN
1032,2024-11-07,Oeste,NaN,Raton Ergo,Accesorios,9,45.0,0.00
1076,2024-11-24,Sur,Sofia Leon,Tablet Air,Tecnologia,7,640.0,NaN
1174,2024-12-22,Norte,NaN,Laptop Pro,Tecnologia,14,1200.0,0.00
1184,2024-12-27,Oeste,Luis Gomez,Escritorio,Mobiliario,10,450.0,NaN

In [11]:
ventas_sin_nulos=ventas.dropna()
ventas_sin_nulos

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130.0,0.00
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320.0,0.00
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280.0,0.00
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200.0,0.00
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130.0,0.10
...,...,...,...,...,...,...,...,...
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45.0,0.00
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200.0,0.05
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320.0,0.05
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320.0,0.00
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45.0,0.00

In [12]:
ventas_sin_nulos_por_columnas=ventas.dropna(subset="vendedor")
ventas_sin_nulos_por_columnas

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130.0,0.00
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320.0,0.00
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280.0,0.00
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200.0,0.00
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130.0,0.10
...,...,...,...,...,...,...,...,...
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45.0,0.00
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200.0,0.05
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320.0,0.05
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320.0,0.00
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45.0,0.00

In [ ]:
ventas.dropna(axis=1)# elimina las columnas que contengan almenos un valor nulo

           fecha  region     producto   categoria  unidades  precio_unitario
0     2024-01-02   Oeste  Auriculares  Accesorios         5            130.0
1     2024-01-02     Sur   Monitor 27  Tecnologia        14            320.0
2     2024-01-02  Centro   Silla Ergo  Mobiliario         1            280.0
3     2024-01-02  Centro   Laptop Pro  Tecnologia        10           1200.0
4     2024-01-03     Sur  Auriculares  Accesorios         2            130.0
...          ...     ...          ...         ...       ...              ...
1195  2024-12-30    Este   Raton Ergo  Accesorios         4             45.0
1196  2024-12-30    Este   Laptop Pro  Tecnologia        13           1200.0
1197  2024-12-31   Oeste   Monitor 27  Tecnologia         2            320.0
1198  2024-12-31   Norte   Monitor 27  Tecnologia         6            320.0
1199  2024-12-31   Norte   Raton Ergo  Accesorios         8             45.0

[1200 rows x 6 columns]

In [16]:
ventas[ventas["descuento"].isna()]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
33,2024-01-11,Sur,Javier Sanz,Laptop Pro,Tecnologia,5,1200.0,NaN
72,2024-01-25,Oeste,Ana Torres,Teclado Mec,Accesorios,12,95.0,NaN
78,2024-01-28,Sur,Pedro Diaz,Tablet Air,Tecnologia,3,640.0,NaN
82,2024-01-30,Oeste,Pedro Diaz,Laptop Pro,Tecnologia,7,1200.0,NaN
98,2024-02-03,Centro,Ana Torres,Monitor 27,Tecnologia,1,320.0,NaN
102,2024-02-03,Norte,Ana Torres,Raton Ergo,Accesorios,11,45.0,NaN
109,2024-02-04,Este,Ana Torres,Raton Ergo,Accesorios,12,45.0,NaN
123,2024-02-09,Este,Sofia Leon,Silla Ergo,Mobiliario,14,280.0,NaN
135,2024-02-13,Este,Marta Ruiz,Laptop Pro,Tecnologia,8,1200.0,NaN
222,2024-03-04,Centro,Marta Ruiz,Laptop Pro,Tecnologia,12,1200.0,NaN
224,2024-03-05,Centro,Ana Torres,Raton Ergo,Accesorios,1,45.0,NaN
239,2024-03-11,Este,Javier Sanz,Escritorio,Mobiliario,3,450.0,NaN
271,2024-03-26,Sur,Javier Sanz,Silla Ergo,Mobiliario,11,280.0,NaN
283,2024-03-28,Este,Javier Sanz,Tablet Air,Tecnologia,2,640.0,NaN
310,2024-04-08,Oeste,Sofia Leon,Laptop Pro,Tecnologia,10,1200.0,NaN
405,2024-05-05,Norte,Carlos Vega,Escritorio,Mobiliario,9,450.0,NaN
424,2024-05-14,Centro,Sofia Leon,Monitor 27,Tecnologia,9,320.0,NaN
530,2024-06-16,Este,Ana Torres,Teclado Mec,Accesorios,9,95.0,NaN
535,2024-06-17,Este,Luis Gomez,Escritorio,Mobiliario,1,450.0,NaN
635,2024-07-14,Centro,Pedro Diaz,Monitor 27,Tecnologia,5,320.0,NaN
668,2024-07-23,Sur,Javier Sanz,Auriculares,Accesorios,6,130.0,NaN
678,2024-07-27,Norte,Marta Ruiz,Laptop Pro,Tecnologia,3,1200.0,NaN
720,2024-08-09,Norte,Elena Mora,Teclado Mec,Accesorios,8,95.0,NaN
795,2024-09-01,Oeste,Ana Torres,Silla Ergo,Mobiliario,6,280.0,NaN
803,2024-09-04,Sur,Ana Torres,Auriculares,Accesorios,5,130.0,NaN
814,2024-09-07,Este,Marta Ruiz,Escritorio,Mobiliario,6,450.0,NaN
830,2024-09-13,Sur,Javier Sanz,Monitor 27,Tecnologia,9,320.0,NaN
876,2024-09-26,Norte,Carlos Vega,Escritorio,Mobiliario,2,450.0,NaN
881,2024-09-27,Norte,Marta Ruiz,Silla Ergo,Mobiliario,7,280.0,NaN
884,2024-09-27,Este,Marta Ruiz,Escritorio,Mobiliario,7,450.0,NaN
904,2024-10-05,Sur,Ana Torres,Tablet Air,Tecnologia,6,640.0,NaN
942,2024-10-14,Este,Pedro Diaz,Teclado Mec,Accesorios,2,95.0,NaN
991,2024-10-29,Sur,NaN,Silla Ergo,Mobiliario,1,280.0,NaN
1076,2024-11-24,Sur,Sofia Leon,Tablet Air,Tecnologia,7,640.0,NaN
1184,2024-12-27,Oeste,Luis Gomez,Escritorio,Mobiliario,10,450.0,NaN

In [18]:
promedio=ventas["descuento"].mean()
promedio

np.float64(0.04763948497854077)

In [19]:
ventas["descuento"].unique()

array([0.  , 0.1 , 0.05, 0.15,  nan])

In [20]:
ventas["descuento"]=ventas["descuento"].fillna(promedio)

In [21]:
ventas["descuento"].unique()

array([0.        , 0.1       , 0.05      , 0.15      , 0.04763948])

In [22]:
ventas.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   fecha            1200 non-null   str
 1   region           1200 non-null   str
 2   vendedor         1182 non-null   str
 3   producto         1200 non-null   str
 4   categoria        1200 non-null   str
 5   unidades         1200 non-null   int64
 6   precio_unitario  1200 non-null   float64
 7   descuento        1200 non-null   float64
dtypes: float64(2), int64(1), str(5)
memory usage: 75.1 KB

In [23]:
ventas[ventas["vendedor"].isna()]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
79,2024-01-29,Oeste,NaN,Raton Ergo,Accesorios,14,45.0,0.100000
161,2024-02-18,Oeste,NaN,Silla Ergo,Mobiliario,1,280.0,0.050000
203,2024-02-28,Norte,NaN,Raton Ergo,Accesorios,4,45.0,0.100000
456,2024-05-28,Oeste,NaN,Tablet Air,Tecnologia,5,640.0,0.000000
549,2024-06-20,Oeste,NaN,Raton Ergo,Accesorios,14,45.0,0.100000
553,2024-06-22,Norte,NaN,Raton Ergo,Accesorios,7,45.0,0.050000
571,2024-06-28,Este,NaN,Laptop Pro,Tecnologia,13,1200.0,0.000000
577,2024-06-29,Este,NaN,Tablet Air,Tecnologia,8,640.0,0.000000
639,2024-07-16,Norte,NaN,Raton Ergo,Accesorios,5,45.0,0.100000
660,2024-07-21,Sur,NaN,Monitor 27,Tecnologia,14,320.0,0.000000
746,2024-08-18,Centro,NaN,Escritorio,Mobiliario,13,450.0,0.150000
758,2024-08-20,Centro,NaN,Silla Ergo,Mobiliario,14,280.0,0.000000
781,2024-08-28,Norte,NaN,Laptop Pro,Tecnologia,5,1200.0,0.000000
935,2024-10-12,Sur,NaN,Laptop Pro,Tecnologia,8,1200.0,0.150000
958,2024-10-18,Oeste,NaN,Monitor 27,Tecnologia,13,320.0,0.150000
991,2024-10-29,Sur,NaN,Silla Ergo,Mobiliario,1,280.0,0.047639
1032,2024-11-07,Oeste,NaN,Raton Ergo,Accesorios,9,45.0,0.000000
1174,2024-12-22,Norte,NaN,Laptop Pro,Tecnologia,14,1200.0,0.000000

In [25]:
ventas[["vendedor","region"]].value_counts()

vendedor     region
Ana Torres   Norte     53
Marta Ruiz   Centro    48
Pedro Diaz   Norte     46
Marta Ruiz   Oeste     39
Sofia Leon   Centro    39
Luis Gomez   Norte     38
Carlos Vega  Norte     37
Pedro Diaz   Centro    36
Ana Torres   Centro    35
Marta Ruiz   Norte     35
Carlos Vega  Centro    33
Elena Mora   Sur       32
Sofia Leon   Sur       32
Ana Torres   Sur       32
Pedro Diaz   Sur       31
Javier Sanz  Sur       31
             Norte     31
Sofia Leon   Norte     30
Javier Sanz  Centro    30
Elena Mora   Norte     30
Luis Gomez   Este      30
Carlos Vega  Sur       29
Sofia Leon   Oeste     28
Elena Mora   Este      28
             Centro    27
Sofia Leon   Este      27
Marta Ruiz   Sur       26
Javier Sanz  Oeste     25
Pedro Diaz   Oeste     24
Luis Gomez   Sur       24
Ana Torres   Este      23
Marta Ruiz   Este      22
Luis Gomez   Centro    22
Ana Torres   Oeste     22
Luis Gomez   Oeste     21
Javier Sanz  Este      20
Elena Mora   Oeste     20
Carlos Vega  Oeste     18
             Este      15
Pedro Diaz   Este      13
Name: count, dtype: int64

In [26]:
ventas["vendedor"].value_counts()

vendedor
Marta Ruiz     170
Ana Torres     165
Sofia Leon     156
Pedro Diaz     150
Elena Mora     137
Javier Sanz    137
Luis Gomez     135
Carlos Vega    132
Name: count, dtype: int64

In [27]:
ventas["vendedor"]=ventas["vendedor"].fillna("Marta Ruiz")

In [28]:
ventas["vendedor"].value_counts()

vendedor
Marta Ruiz     188
Ana Torres     165
Sofia Leon     156
Pedro Diaz     150
Elena Mora     137
Javier Sanz    137
Luis Gomez     135
Carlos Vega    132
Name: count, dtype: int64

In [29]:
ventas.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   fecha            1200 non-null   str
 1   region           1200 non-null   str
 2   vendedor         1200 non-null   str
 3   producto         1200 non-null   str
 4   categoria        1200 non-null   str
 5   unidades         1200 non-null   int64
 6   precio_unitario  1200 non-null   float64
 7   descuento        1200 non-null   float64
dtypes: float64(2), int64(1), str(5)
memory usage: 75.1 KB

In [30]:
ventas = pd.read_csv(r"C:\Users\SAHUA\Documents\datascience-g8\01-python-intro\data\ventas.csv",
    dtype={"precio_unitario":"float64"})

In [31]:
ventas.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   fecha            1200 non-null   str
 1   region           1200 non-null   str
 2   vendedor         1182 non-null   str
 3   producto         1200 non-null   str
 4   categoria        1200 non-null   str
 5   unidades         1200 non-null   int64
 6   precio_unitario  1200 non-null   float64
 7   descuento        1165 non-null   float64
dtypes: float64(2), int64(1), str(5)
memory usage: 75.1 KB

In [33]:
#calcular el porcentaje de nulos por columna en venatas.csv
ventas.isna().mean()*100

fecha              0.000000
region             0.000000
vendedor           1.500000
producto           0.000000
categoria          0.000000
unidades           0.000000
precio_unitario    0.000000
descuento          2.916667
dtype: float64

In [34]:
#Rellenar descuento con 0 y jsutificar en un comentario porque es razonable
ventas["descuento"]=ventas["descuento"].fillna(0)

In [35]:
ventas["descuento"].value_counts()

descuento
0.00    626
0.05    213
0.10    186
0.15    175
Name: count, dtype: int64

In [37]:
#Rellena vendedor con 'Sin asignar' sin perder ninguna fila
ventas["vendedor"].fillna("Sin asignar",inplace=True)# es igua a ventas["vendedor"]=ventas["vendedor"].fillna("Sin asignar")
ventas.info()
#en empleados, rellena la nota vacia con la mediana de la columna
empleados=pd.read_csv(r"C:\Users\SAHUA\Documents\datascience-g8\01-python-intro\data\empleados.csv")
mediana=empleados["evaluacion"].median()
empleados["evaluacion"]=empleados["evaluacion"].fillna(mediana)
#Crea una copia de empleados eliminando las filas sin nota y compara cuantas filas pierdes

#comprueba con isna().sum() que ya no queda ningun nulo
empleados.isna().sum()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   fecha            1200 non-null   str
 1   region           1200 non-null   str
 2   vendedor         1182 non-null   str
 3   producto         1200 non-null   str
 4   categoria        1200 non-null   str
 5   unidades         1200 non-null   int64
 6   precio_unitario  1200 non-null   float64
 7   descuento        1200 non-null   float64
dtypes: float64(2), int64(1), str(5)
memory usage: 75.1 KB

C:\Users\SAHUA\AppData\Local\Temp\ipykernel_40984\2800115808.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  ventas["vendedor"].fillna("Sin asignar",inplace=True)# es igua a ventas["vendedor"]=ventas["vendedor"].fillna("Sin asignar")

id_empleado           0
nombre                0
departamento          0
ciudad                0
salario               0
fecha_contratacion    0
evaluacion            0
dtype: int64

In [38]:
#comprueba con isna().sum() que ya no queda ningun nulo
empleados.isna().sum()

id_empleado           0
nombre                0
departamento          0
ciudad                0
salario               0
fecha_contratacion    0
evaluacion            0
dtype: int64