In [99]:
import pandas as pd
url = "https://raw.githubusercontent.com/allisonhorst/palmerpenguins/main/inst/extdata/penguins.csv"
df = pd.read_csv(url)

In [100]:
df.head(20)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,male,2007
6,Adelie,Torgersen,38.9,17.8,181.0,3625.0,female,2007
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,male,2007
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN,2007
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN,2007
10,Adelie,Torgersen,37.8,17.1,186.0,3300.0,NaN,2007
11,Adelie,Torgersen,37.8,17.3,180.0,3700.0,NaN,2007
12,Adelie,Torgersen,41.1,17.6,182.0,3200.0,female,2007
13,Adelie,Torgersen,38.6,21.2,191.0,3800.0,male,2007
14,Adelie,Torgersen,34.6,21.1,198.0,4400.0,male,2007
15,Adelie,Torgersen,36.6,17.8,185.0,3700.0,female,2007
16,Adelie,Torgersen,38.7,19.0,195.0,3450.0,female,2007
17,Adelie,Torgersen,42.5,20.7,197.0,4500.0,male,2007
18,Adelie,Torgersen,34.4,18.4,184.0,3325.0,female,2007
19,Adelie,Torgersen,46.0,21.5,194.0,4200.0,male,2007

In [101]:
df.shape

(344, 8)

In [102]:
df["species"].value_counts()

species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64

In [103]:
df["sex"].value_counts()

sex
male      168
female    165
Name: count, dtype: int64

In [104]:
df.head(5)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007

In [105]:
# Ultimas 8 filas 
df.tail(8)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
336,Chinstrap,Dream,51.9,19.5,206.0,3950.0,male,2009
337,Chinstrap,Dream,46.8,16.5,189.0,3650.0,female,2009
338,Chinstrap,Dream,45.7,17.0,195.0,3650.0,female,2009
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

In [106]:
# 4 - filas y columnas 
df.shape

(344, 8)

In [107]:
#5- columnas
list(df.columns)

['species',
 'island',
 'bill_length_mm',
 'bill_depth_mm',
 'flipper_length_mm',
 'body_mass_g',
 'sex',
 'year']

In [108]:
#6- datos de cada columna
df.dtypes

species                  str
island                   str
bill_length_mm       float64
bill_depth_mm        float64
flipper_length_mm    float64
body_mass_g          float64
sex                      str
year                   int64
dtype: object

In [109]:
#7- info general
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   island             344 non-null    str
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    str
 7   year               344 non-null    int64
dtypes: float64(4), int64(1), str(3)
memory usage: 21.6 KB

In [110]:
#8 - estadisticas descriptivas 
df.describe()

,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,year
count,342.000000,342.000000,342.000000,342.000000,344.000000
mean,43.921930,17.151170,200.915205,4201.754386,2008.029070
std,5.459584,1.974793,14.061714,801.954536,0.818356
min,32.100000,13.100000,172.000000,2700.000000,2007.000000
25%,39.225000,15.600000,190.000000,3550.000000,2007.000000
50%,44.450000,17.300000,197.000000,4050.000000,2008.000000
75%,48.500000,18.700000,213.000000,4750.000000,2009.000000
max,59.600000,21.500000,231.000000,6300.000000,2009.000000

In [111]:
#9 - seleccion de columnas
penguins_mass=df[["species","island","body_mass_g"]]
penguins_mass

       species     island  body_mass_g
0       Adelie  Torgersen       3750.0
1       Adelie  Torgersen       3800.0
2       Adelie  Torgersen       3250.0
3       Adelie  Torgersen          NaN
4       Adelie  Torgersen       3450.0
..         ...        ...          ...
339  Chinstrap      Dream       4000.0
340  Chinstrap      Dream       3400.0
341  Chinstrap      Dream       3775.0
342  Chinstrap      Dream       4100.0
343  Chinstrap      Dream       3775.0

[344 rows x 3 columns]

In [112]:
#10 - valores unicos
df["species"].value_counts()

species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64

In [113]:
#11 - valores unicos
df["species"].value_counts()

species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64

In [114]:
#12- conteo island
df["island"].value_counts()

island
Biscoe       168
Dream        124
Torgersen     52
Name: count, dtype: int64

In [115]:
# 13. Filtro simple 
# Obtén todos los pingüinos cuya masa corporal sea superior a 5000 gramos. 
filtrado=df[df["body_mass_g"]>5000]
filtrado

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
153,Gentoo,Biscoe,50.0,16.3,230.0,5700.0,male,2007
155,Gentoo,Biscoe,50.0,15.2,218.0,5700.0,male,2007
156,Gentoo,Biscoe,47.6,14.5,215.0,5400.0,male,2007
159,Gentoo,Biscoe,46.7,15.3,219.0,5200.0,male,2007
161,Gentoo,Biscoe,46.8,15.4,215.0,5150.0,male,2007
...,...,...,...,...,...,...,...,...
267,Gentoo,Biscoe,55.1,16.0,230.0,5850.0,male,2009
269,Gentoo,Biscoe,48.8,16.2,222.0,6000.0,male,2009
273,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,male,2009
274,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,female,2009
275,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,male,2009

In [116]:
filtrado["body_mass_g"].min()

np.float64(5050.0)

In [117]:
# 14. Filtro por categoría 
# Obtén únicamente los pingüinos de especie Gentoo.
filtrado=df[df["species"]=="Gentoo"]
filtrado

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
152,Gentoo,Biscoe,46.1,13.2,211.0,4500.0,female,2007
153,Gentoo,Biscoe,50.0,16.3,230.0,5700.0,male,2007
154,Gentoo,Biscoe,48.7,14.1,210.0,4450.0,female,2007
155,Gentoo,Biscoe,50.0,15.2,218.0,5700.0,male,2007
156,Gentoo,Biscoe,47.6,14.5,215.0,5400.0,male,2007
...,...,...,...,...,...,...,...,...
271,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,2009
272,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,female,2009
273,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,male,2009
274,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,female,2009
275,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,male,2009

In [118]:
# 15. Múltiples condiciones 
# Obtén los pingüinos que cumplan simultáneamente: species == "Gentoo" y body_mass_g > 5000.
filtrado=df[(df["species"]=="Gentoo")&(df["body_mass_g"]>5000)]
filtrado

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
153,Gentoo,Biscoe,50.0,16.3,230.0,5700.0,male,2007
155,Gentoo,Biscoe,50.0,15.2,218.0,5700.0,male,2007
156,Gentoo,Biscoe,47.6,14.5,215.0,5400.0,male,2007
159,Gentoo,Biscoe,46.7,15.3,219.0,5200.0,male,2007
161,Gentoo,Biscoe,46.8,15.4,215.0,5150.0,male,2007
...,...,...,...,...,...,...,...,...
267,Gentoo,Biscoe,55.1,16.0,230.0,5850.0,male,2009
269,Gentoo,Biscoe,48.8,16.2,222.0,6000.0,male,2009
273,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,male,2009
274,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,female,2009
275,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,male,2009

In [119]:
filtrado["species"].unique()

<StringArray>
['Gentoo']
Length: 1, dtype: str

In [120]:
filtrado["body_mass_g"].min()

np.float64(5050.0)

In [121]:
# 16. Condición OR 
# Obtén los registros correspondientes a pingüinos de las especies Adelie o Chinstrap. Intenta resolverlo sin 
# crear dos DataFrames separados. 
filtrado=df[(df["species"]=="Adelie")|(df["species"]=="Chinstrap")]
filtrado

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

In [122]:
filtrado["species"].unique()

<StringArray>
['Adelie', 'Chinstrap']
Length: 2, dtype: str

In [123]:
# 17. Ordenamiento 
# Ordena el dataset de mayor a menor utilizando body_mass_g. 
df.sort_values("body_mass_g", ascending=False)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
169,Gentoo,Biscoe,49.2,15.2,221.0,6300.0,male,2007
185,Gentoo,Biscoe,59.6,17.0,230.0,6050.0,male,2007
269,Gentoo,Biscoe,48.8,16.2,222.0,6000.0,male,2009
229,Gentoo,Biscoe,51.1,16.3,220.0,6000.0,male,2008
231,Gentoo,Biscoe,45.2,16.4,223.0,5950.0,male,2008
...,...,...,...,...,...,...,...,...
58,Adelie,Biscoe,36.5,16.6,181.0,2850.0,female,2008
64,Adelie,Biscoe,36.4,17.1,184.0,2850.0,female,2008
314,Chinstrap,Dream,46.9,16.6,192.0,2700.0,female,2008
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
271,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,2009

In [124]:
# 18. Top 10 
# Encuentra los 10 pingüinos con mayor masa corporal. Muestra solamente species, island, sex y 
# body_mass_g.
df.sort_values("body_mass_g", ascending=False).loc[:,["species","island","sex","body_mass_g"]].iloc[:10,:]

    species  island   sex  body_mass_g
169  Gentoo  Biscoe  male       6300.0
185  Gentoo  Biscoe  male       6050.0
269  Gentoo  Biscoe  male       6000.0
229  Gentoo  Biscoe  male       6000.0
231  Gentoo  Biscoe  male       5950.0
263  Gentoo  Biscoe  male       5950.0
165  Gentoo  Biscoe  male       5850.0
267  Gentoo  Biscoe  male       5850.0
167  Gentoo  Biscoe  male       5850.0
219  Gentoo  Biscoe  male       5800.0

In [125]:
# 19. Valores nulos 
# Determina cuántos valores faltantes existen en cada columna.
df.isna().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
year                  0
dtype: int64

In [126]:
df.isna()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,True,True,True,True,True,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
339,False,False,False,False,False,False,False,False
340,False,False,False,False,False,False,False,False
341,False,False,False,False,False,False,False,False
342,False,False,False,False,False,False,False,False
343,False,False,False,False,False,False,False,False

In [127]:
# 20. Eliminar valores faltantes 
# Crea un DataFrame llamado df_clean que elimine únicamente los registros que tengan valores faltantes en 
# sex o body_mass_g. Comprueba cuántas filas fueron eliminadas. 
df_clean=df.dropna(subset=["sex","body_mass_g"])
df_clean

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,male,2007
...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

In [128]:
# 21. Crear una nueva columna 
# Crea una columna llamada body_mass_kg con la masa corporal expresada en kilogramos. Recuerda: 1000 
# g = 1 kg. No modifiques body_mass_g. 
df["body_mass_kg"]=df["body_mass_g"]/1000
df.head(10)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,body_mass_kg
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007,3.750
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007,3.800
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007,3.250
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007,3.450
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,male,2007,3.650
6,Adelie,Torgersen,38.9,17.8,181.0,3625.0,female,2007,3.625
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,male,2007,4.675
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN,2007,3.475
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN,2007,4.250

In [129]:
# 22. Clasificación mediante pd.cut() 
# Crea una nueva columna mass_category clasificando los pingüinos como Light si pesan menos de 3500 g, 
# Medium si pesan entre 3500 y 4500 g (inclusive) y Heavy si pesan más de 4500 g. Utiliza pd.cut(). 
df["mass_category"] = pd.cut(
    df["body_mass_g"],
    bins=[-float("inf"), 3500, 4500, float("inf")],# rango de -infinito a 3500 a 4500 a mas inifinito
    labels=["Light", "Medium", "Heavy"]
)

df.head(10)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,body_mass_kg,mass_category
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007,3.750,Medium
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007,3.800,Medium
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007,3.250,Light
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007,3.450,Light
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,male,2007,3.650,Medium
6,Adelie,Torgersen,38.9,17.8,181.0,3625.0,female,2007,3.625,Medium
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,male,2007,4.675,Heavy
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN,2007,3.475,Light
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN,2007,4.250,Medium

In [130]:
# 23. Masa promedio por especie 
# Calcula la masa corporal promedio (body_mass_g) de cada especie. El resultado debe tener una fila por 
# especie. 
agrupado=df.groupby("species")["body_mass_g"].agg(Promedio ="mean")
agrupado

              Promedio
species
Adelie     3700.662252
Chinstrap  3733.088235
Gentoo     5076.016260

In [131]:
# 24. Múltiples estadísticas 
# Para cada especie calcula sobre body_mass_g: cantidad, promedio, mínimo, máximo y desviación estándar. 
# Intenta resolverlo utilizando groupby() y agg(). 
agrupado=df.groupby("species")["body_mass_g"].agg([
    "count",
    "mean",
    "min",
    "max",
    "std"
])
agrupado

           count         mean     min     max         std
species
Adelie       151  3700.662252  2850.0  4775.0  458.566126
Chinstrap     68  3733.088235  2700.0  4800.0  384.335081
Gentoo       123  5076.016260  3950.0  6300.0  504.116237

In [132]:
# 25. Agrupación utilizando dos columnas 
# Calcula la masa corporal promedio agrupando por species y sex. El resultado debe permitir comparar 
# machos y hembras dentro de cada especie. 
agrupado=df.groupby(["species","sex"])["body_mass_g"].agg([
    "count",
    "mean",
    "min",
    "max",
    "std"
])
agrupado

                  count         mean     min     max         std
species   sex
Adelie    female     73  3368.835616  2850.0  3900.0  269.380102
          male       73  4043.493151  3325.0  4775.0  346.811553
Chinstrap female     34  3527.205882  2700.0  4150.0  285.333912
          male       34  3938.970588  3250.0  4800.0  362.137550
Gentoo    female     58  4679.741379  3950.0  5200.0  281.578294
          male       61  5484.836066  4750.0  6300.0  313.158596

In [133]:
# 26. Tabla cruzada 
# Construye una tabla que muestre cuántos pingüinos existen para cada combinación species × island. 
# Puedes utilizar pd.crosstab() o pivot_table(). 
pd.crosstab(df["species"], df["island"])

island     Biscoe  Dream  Torgersen
species
Adelie         44     56         52
Chinstrap       0     68          0
Gentoo        124      0          0

In [134]:
# 27. Pingüino más pesado de cada especie
# Encuentra el registro correspondiente al pingüino con mayor body_mass_g dentro de cada especie. El
# resultado final debe mostrar species, sex, island y body_mass_g. No basta con mostrar únicamente la masa
# máxima: debes recuperar el registro completo correspondiente al máximo.

indices=df.groupby("species")["body_mass_g"].idxmax()
df.loc[indices]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,body_mass_kg,mass_category
109,Adelie,Biscoe,43.2,19.0,197.0,4775.0,male,2009,4.775,Heavy
313,Chinstrap,Dream,52.0,20.7,210.0,4800.0,male,2008,4.800,Heavy
169,Gentoo,Biscoe,49.2,15.2,221.0,6300.0,male,2007,6.300,Heavy

In [135]:
df.groupby("species")["body_mass_g"].max()

species
Adelie       4775.0
Chinstrap    4800.0
Gentoo       6300.0
Name: body_mass_g, dtype: float64

In [136]:
df.loc[109,:]

species              Adelie
island               Biscoe
bill_length_mm         43.2
bill_depth_mm          19.0
flipper_length_mm     197.0
body_mass_g          4775.0
sex                    male
year                   2009
body_mass_kg          4.775
mass_category         Heavy
Name: 109, dtype: object

In [137]:
df.loc[313,:]

species              Chinstrap
island                   Dream
bill_length_mm            52.0
bill_depth_mm             20.7
flipper_length_mm        210.0
body_mass_g             4800.0
sex                       male
year                      2008
body_mass_kg               4.8
mass_category            Heavy
Name: 313, dtype: object

In [138]:
# 28. Diferencia respecto al promedio 
# Crea una columna mass_difference que indique cuánto pesa cada pingüino por encima o por debajo del 
# promedio de su propia especie. Conceptualmente: masa del pingüino - masa promedio de su especie. 
# Intenta resolverlo usando groupby() y transform(). 
df["mass_difference"] = (
    df["body_mass_g"] -
    df.groupby("species")["body_mass_g"].transform("mean")#lo devuelve repetido en cada fila en cada elemento
)
df.head(10)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,body_mass_kg,mass_category,mass_difference
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007,3.750,Medium,49.337748
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007,3.800,Medium,99.337748
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007,3.250,Light,-450.662252
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007,3.450,Light,-250.662252
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,male,2007,3.650,Medium,-50.662252
6,Adelie,Torgersen,38.9,17.8,181.0,3625.0,female,2007,3.625,Medium,-75.662252
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,male,2007,4.675,Heavy,974.337748
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN,2007,3.475,Light,-225.662252
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN,2007,4.250,Medium,549.337748

In [139]:
# 29. Ranking dentro de cada especie 
# Crea una columna mass_rank que indique el ranking de masa corporal de cada pingüino dentro de su propia 
# especie. El pingüino más pesado debe tener mass_rank = 1. Luego muestra los 3 pingüinos más pesados de 
# cada especie. 
df["mass_rank"] = (
    df.groupby("species")["body_mass_g"].rank(method="min", ascending=False)
)

df[df["mass_rank"] <= 3].sort_values(["species", "mass_rank"])

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,body_mass_kg,mass_category,mass_difference,mass_rank
109,Adelie,Biscoe,43.2,19.0,197.0,4775.0,male,2009,4.775,Heavy,1074.337748,1.0
101,Adelie,Biscoe,41.0,20.0,203.0,4725.0,male,2009,4.725,Heavy,1024.337748,2.0
81,Adelie,Torgersen,42.9,17.6,196.0,4700.0,male,2008,4.700,Heavy,999.337748,3.0
313,Chinstrap,Dream,52.0,20.7,210.0,4800.0,male,2008,4.800,Heavy,1066.911765,1.0
305,Chinstrap,Dream,52.8,20.0,205.0,4550.0,male,2008,4.550,Heavy,816.911765,2.0
315,Chinstrap,Dream,53.5,19.9,205.0,4500.0,male,2008,4.500,Medium,766.911765,3.0
169,Gentoo,Biscoe,49.2,15.2,221.0,6300.0,male,2007,6.300,Heavy,1223.983740,1.0
185,Gentoo,Biscoe,59.6,17.0,230.0,6050.0,male,2007,6.050,Heavy,973.983740,2.0
229,Gentoo,Biscoe,51.1,16.3,220.0,6000.0,male,2008,6.000,Heavy,923.983740,3.0
269,Gentoo,Biscoe,48.8,16.2,222.0,6000.0,male,2009,6.000,Heavy,923.983740,3.0

In [140]:
# 30. Ejercicio integrador — Reporte de especies
# Construye un DataFrame llamado species_report con una fila por especie y las columnas: species,
# total_penguins, average_body_mass, min_body_mass, max_body_mass, average_flipper_length y
# average_bill_length. Redondea los promedios a 2 decimales. Luego ordénalo de mayor a menor por
# average_body_mass, identifica la especie con mayor masa promedio y la especie con mayor longitud
# promedio de aleta, y guarda el resultado en species_report.csv sin incluir el índice.

# agrupado=df.groupby("species")["body_mass_g"].agg([
#     "count",
#     "mean",
#     "min",
#     "max",
#     "std"
# ])
dataframe=df.groupby("species").agg(
    total_pinguinos=("body_mass_g", "count"),
    average_body_mass=("body_mass_g", "mean"),
    min_body_mass=("body_mass_g", "min"),
    max_body_mass=("body_mass_g", "max"),
    average_flipper=("flipper_length_mm", "mean"),
    average_bill_length=("bill_length_mm", "mean")
).round(2).sort_values("average_body_mass",ascending=False)
dataframe

,total_pinguinos,average_body_mass,min_body_mass,max_body_mass,average_flipper,average_bill_length
species,,,,,,
Gentoo,123,5076.02,3950.0,6300.0,217.19,47.50
Chinstrap,68,3733.09,2700.0,4800.0,195.82,48.83
Adelie,151,3700.66,2850.0,4775.0,189.95,38.79

In [141]:
# mayor masa promedio 
dataframe.iloc[0]

total_pinguinos         123.00
average_body_mass      5076.02
min_body_mass          3950.00
max_body_mass          6300.00
average_flipper         217.19
average_bill_length      47.50
Name: Gentoo, dtype: float64

In [142]:
dataframe["average_body_mass"].idxmax()

'Gentoo'

In [143]:
#mayor longitud promedio de aleta
dataframe.sort_values("average_flipper",ascending=False).iloc[0]

total_pinguinos         123.00
average_body_mass      5076.02
min_body_mass          3950.00
max_body_mass          6300.00
average_flipper         217.19
average_bill_length      47.50
Name: Gentoo, dtype: float64

In [144]:
dataframe["average_flipper"].idxmax()

'Gentoo'

In [145]:
species_report = df.groupby("species").agg(
    total_penguins=("body_mass_g", "count"),
    average_body_mass=("body_mass_g", "mean"),
    min_body_mass=("body_mass_g", "min"),
    max_body_mass=("body_mass_g", "max"),
    average_flipper_length=("flipper_length_mm", "mean"),
    average_bill_length=("bill_length_mm", "mean")
).round(2).sort_values("average_body_mass", ascending=False).reset_index()

species_report

,species,total_penguins,average_body_mass,min_body_mass,max_body_mass,average_flipper_length,average_bill_length
0,Gentoo,123,5076.02,3950.0,6300.0,217.19,47.50
1,Chinstrap,68,3733.09,2700.0,4800.0,195.82,48.83
2,Adelie,151,3700.66,2850.0,4775.0,189.95,38.79

In [146]:
species_report.loc[species_report["average_body_mass"].idxmax(), "species"]
species_report.loc[species_report["average_flipper_length"].idxmax(), "species"]

'Gentoo'

In [147]:
species_report.to_csv("species_report.csv", index=False)

In [148]:
mayor_peso = species_report.iloc[[0]]
mayor_peso.to_csv("especie_mayor_peso.csv", index=False)