In [11]:
import pandas as pd
empleados=pd.read_csv(r"C:\Users\SAHUA\Documents\datascience-g8\01-python-intro\data\empleados.csv",index_col="id_empleado")

In [ ]:
empleados.head(20)##empleados.set_index("id_empleado")

,nombre,departamento,ciudad,salario,fecha_contratacion,evaluacion
id_empleado,,,,,,
1001,Marta Ruiz,Finanzas,Valencia,44300.0,2024-06-12,2.0
1002,Elena Sanz,RRHH,Madrid,22000.0,2022-08-16,1.0
1003,Ana Prieto,Ventas,Bilbao,58200.0,2024-02-21,4.0
1004,Laura Gomez,Marketing,Sevilla,24900.0,2023-05-21,3.0
1005,Paula Torres,RRHH,Madrid,54800.0,2019-01-18,5.0
1006,Lucia Mora,Finanzas,Valencia,49200.0,2022-03-25,3.0
1007,Javier Nieto,IT,Valencia,44400.0,2015-04-20,NaN
1008,Sergio Leon,Operaciones,Barcelona,28600.0,2020-07-01,2.0
1009,Lucia Nieto,Operaciones,Madrid,39700.0,2015-06-20,1.0
1010,Laura Lara,Finanzas,Sevilla,32800.0,2022-02-20,5.0
1011,Elena Leon,IT,Barcelona,38300.0,2024-07-12,5.0
1012,Javier Prieto,Operaciones,Valencia,35300.0,2021-09-19,1.0
1013,Sergio Ferrer,Finanzas,Barcelona,22000.0,2023-04-12,4.0
1014,Laura Sanz,RRHH,Sevilla,50300.0,2017-04-23,2.0
1015,Sofia Mora,IT,Madrid,37100.0,2024-10-18,3.0
1016,Javier Prieto,Finanzas,Barcelona,32700.0,2020-06-05,5.0
1017,Lucia Cano,RRHH,Valencia,31800.0,2021-08-25,5.0
1018,Ana Cano,Marketing,Valencia,41900.0,2022-08-06,1.0
1019,Javier Nieto,Operaciones,Sevilla,28200.0,2021-04-21,2.0
1020,Javier Sanz,Ventas,Madrid,22000.0,2018-02-15,5.0

In [13]:
empleados.shape

(90, 6)

In [16]:
# 2. Muestra solo las columnas nombre, departamento y salario
empleados_filtro=empleados[["nombre","departamento","ciudad"]]
empleados_filtro

                   nombre departamento     ciudad
id_empleado
1001           Marta Ruiz     Finanzas   Valencia
1002           Elena Sanz         RRHH     Madrid
1003           Ana Prieto       Ventas     Bilbao
1004          Laura Gomez    Marketing    Sevilla
1005         Paula Torres         RRHH     Madrid
...                   ...          ...        ...
1086         Nuria Torres  Operaciones     Madrid
1087           Diego Sanz         RRHH     Bilbao
1088         Lucia Prieto  Operaciones  Barcelona
1089         Sergio Gomez         RRHH     Bilbao
1090            Ana Gomez    Marketing     Bilbao

[90 rows x 3 columns]

In [ ]:
#3- Muestra las filas 1003,1007,1015
empleados_filtro.loc[[1003,1007,1015]]

                   nombre departamento    ciudad
id_empleado
1003           Ana Prieto       Ventas    Bilbao
1007         Javier Nieto           IT  Valencia
1015           Sofia Mora           IT    Madrid

In [ ]:
# 4-Usas iloc 
empleados.iloc[:10,1:4]

            departamento     ciudad  salario
id_empleado
1001            Finanzas   Valencia  44300.0
1002                RRHH     Madrid  22000.0
1003              Ventas     Bilbao  58200.0
1004           Marketing    Sevilla  24900.0
1005                RRHH     Madrid  54800.0
1006            Finanzas   Valencia  49200.0
1007                  IT   Valencia  44400.0
1008         Operaciones  Barcelona  28600.0
1009         Operaciones     Madrid  39700.0
1010            Finanzas    Sevilla  32800.0

In [ ]:
#5.Ordena la plantilla por salario descendente y quedate con el top 5
empleados.sort_values("salario",ascending=False).iloc[:5]

,nombre,departamento,ciudad,salario,fecha_contratacion,evaluacion
id_empleado,,,,,,
1032,Diego Gomez,Marketing,Madrid,59500.0,2023-07-14,5.0
1053,Laura Torres,IT,Barcelona,59400.0,2016-03-30,1.0
1003,Ana Prieto,Ventas,Bilbao,58200.0,2024-02-21,4.0
1046,Marta Ortiz,Finanzas,Madrid,57500.0,2018-07-03,5.0
1062,Diego Prieto,RRHH,Madrid,55600.0,2015-01-06,1.0

In [ ]:
# 6.Ordena por departamentos
empleados.sort_values(["departamento","salario"],ascending=[True,False])

,nombre,departamento,ciudad,salario,fecha_contratacion,evaluacion
id_empleado,,,,,,
1046,Marta Ortiz,Finanzas,Madrid,57500.0,2018-07-03,5.0
1006,Lucia Mora,Finanzas,Valencia,49200.0,2022-03-25,3.0
1001,Marta Ruiz,Finanzas,Valencia,44300.0,2024-06-12,2.0
1055,Carlos Ortiz,Finanzas,Sevilla,43200.0,2019-07-21,3.0
1039,Marta Gomez,Finanzas,Valencia,42900.0,2016-11-05,1.0
...,...,...,...,...,...,...
1054,Pedro Gomez,Ventas,Madrid,41400.0,2022-02-25,2.0
1063,Sofia Torres,Ventas,Barcelona,40000.0,2019-08-31,NaN
1024,Sergio Torres,Ventas,Madrid,25400.0,2019-09-30,3.0
1020,Javier Sanz,Ventas,Madrid,22000.0,2018-02-15,5.0
1048,Sofia Ferrer,Ventas,Barcelona,22000.0,2017-09-16,2.0

In [26]:
empleados["departamento"].unique()

<StringArray>
['Finanzas', 'RRHH', 'Ventas', 'Marketing', 'IT', 'Operaciones']
Length: 6, dtype: str