In [15]:
## Concatenado

import pandas as pd

enero=pd.DataFrame({
    "mes":["Enero"],
    "num_mes":[1]
})

febrero=pd.DataFrame({
    "mes":["Febrero"],
    "num_mes":[2]
})
marzo=pd.DataFrame({
    "mes":["Marzo"],
    "num_mes":[3]
})

In [16]:
pd.concat([enero,febrero,marzo],axis=1)

     mes  num_mes      mes  num_mes    mes  num_mes
0  Enero        1  Febrero        2  Marzo        3

In [17]:
pd.concat([enero,febrero,marzo],axis=0)

       mes  num_mes
0    Enero        1
0  Febrero        2
0    Marzo        3

## Join

In [18]:
ventas = pd.read_csv(r"C:\Users\SAHUA\Documents\datascience-g8\01-python-intro\data\ventas.csv")

catalogo_prods=pd.read_csv(r"C:\Users\SAHUA\Documents\datascience-g8\01-python-intro\data\catalogo_productos.csv")

In [19]:
ventas.head(3)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.0

In [20]:
catalogo_prods.head(10)

      producto  coste_unitario proveedor  stock
0   Laptop Pro             780  TecnoSur     45
1   Monitor 27             195  TecnoSur    120
2  Teclado Mec              52   InputCo    300
3   Raton Ergo              21   InputCo    500
4   Silla Ergo             160   ErgoLab     80
5   Escritorio             250   ErgoLab     35
6  Auriculares              68   InputCo    210
7   Tablet Air             390  TecnoSur     60

In [21]:
left_join=ventas.merge(catalogo_prods,on="producto",how="left")

In [22]:
left_join

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento,coste_unitario,proveedor,stock
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.00,68,InputCo,210
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.00,195,TecnoSur,120
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.00,160,ErgoLab,80
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.00,780,TecnoSur,45
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.10,68,InputCo,210
...,...,...,...,...,...,...,...,...,...,...,...
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45,0.00,21,InputCo,500
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200,0.05,780,TecnoSur,45
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320,0.05,195,TecnoSur,120
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320,0.00,195,TecnoSur,120
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45,0.00,21,InputCo,500

In [23]:
left_join.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   fecha            1200 non-null   str
 1   region           1200 non-null   str
 2   vendedor         1182 non-null   str
 3   producto         1200 non-null   str
 4   categoria        1200 non-null   str
 5   unidades         1200 non-null   int64
 6   precio_unitario  1200 non-null   int64
 7   descuento        1165 non-null   float64
 8   coste_unitario   1200 non-null   int64
 9   proveedor        1200 non-null   str
 10  stock            1200 non-null   int64
dtypes: float64(1), int64(4), str(6)
memory usage: 103.3 KB

In [24]:
ventas.loc[1199, "producto"] = "Fuente de poder"
ventas.tail(5)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45,0.00
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200,0.05
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320,0.05
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320,0.00
1199,2024-12-31,Norte,Marta Ruiz,Fuente de poder,Accesorios,8,45,0.00

In [25]:
left_join=ventas.merge(catalogo_prods,on="producto",how="left")
left_join

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento,coste_unitario,proveedor,stock
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.00,68.0,InputCo,210.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.00,195.0,TecnoSur,120.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.00,160.0,ErgoLab,80.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.00,780.0,TecnoSur,45.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.10,68.0,InputCo,210.0
...,...,...,...,...,...,...,...,...,...,...,...
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45,0.00,21.0,InputCo,500.0
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200,0.05,780.0,TecnoSur,45.0
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320,0.05,195.0,TecnoSur,120.0
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320,0.00,195.0,TecnoSur,120.0
1199,2024-12-31,Norte,Marta Ruiz,Fuente de poder,Accesorios,8,45,0.00,NaN,NaN,NaN

In [26]:
inner_join=ventas.merge(catalogo_prods,on="producto", how="inner")
inner_join

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento,coste_unitario,proveedor,stock
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.00,68,InputCo,210
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.00,195,TecnoSur,120
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.00,160,ErgoLab,80
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.00,780,TecnoSur,45
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.10,68,InputCo,210
...,...,...,...,...,...,...,...,...,...,...,...
1194,2024-12-30,Norte,Ana Torres,Tablet Air,Tecnologia,4,640,0.00,390,TecnoSur,60
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45,0.00,21,InputCo,500
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200,0.05,780,TecnoSur,45
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320,0.05,195,TecnoSur,120
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320,0.00,195,TecnoSur,120